server:
  port: 8082

spring:
  application:
    name: auth-service
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/test?currentSchema=auth_service}
    username: test
    password: test
    driver-class-name: org.postgresql.Driver

#    url: jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: auth_service
      #   dialect: org.hibernate.dialect.H2Dialect#  //
  flyway:
    schemas: auth_service #  //
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    metadata-map:
      management:
        context-path: /actuator

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,build,git,flyway
  endpoint:
    health:
      show-details: always
